// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/arcade" | "/assets" | "/card-preview" | "/class-enroll" | "/create" | "/dashboard" | "/dev" | "/dreams" | "/exchange" | "/history" | "/life" | "/location-event" | "/location-npcs" | "/login" | "/neighbors" | "/personality" | "/phone" | "/reading" | "/reincarnation" | "/relationships" | "/savings" | "/secret-realm" | "/shop" | "/short-video" | "/spirit-pet" | "/streets" | "/weather" | "/world"
type AppRouteHandlerRoutes = "/api/action" | "/api/activity" | "/api/advance-quarter" | "/api/advance-year" | "/api/alchemy/formulas" | "/api/alchemy/refine" | "/api/arcade" | "/api/auth/admin" | "/api/auth/auto" | "/api/auth/logout" | "/api/class-enroll" | "/api/combat" | "/api/cultivator" | "/api/cultivator/migrate" | "/api/cultivator/techniques" | "/api/cultivator/use-item" | "/api/dream" | "/api/encounter" | "/api/events" | "/api/exchange" | "/api/family" | "/api/family-dialogue" | "/api/heal" | "/api/health" | "/api/location-event" | "/api/location-npc" | "/api/narrative" | "/api/narrative/retry" | "/api/neighbors" | "/api/npc-chat" | "/api/properties" | "/api/reading" | "/api/reincarnation" | "/api/reincarnation-altar" | "/api/resolve-event" | "/api/savings" | "/api/secret-realm" | "/api/settings" | "/api/settings/list-models" | "/api/shop" | "/api/short-video" | "/api/spirit-pet" | "/api/streets" | "/api/talent-slot" | "/api/travel" | "/api/use-item" | "/api/warmup" | "/api/weather"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/action": {}
  "/api/activity": {}
  "/api/advance-quarter": {}
  "/api/advance-year": {}
  "/api/alchemy/formulas": {}
  "/api/alchemy/refine": {}
  "/api/arcade": {}
  "/api/auth/admin": {}
  "/api/auth/auto": {}
  "/api/auth/logout": {}
  "/api/class-enroll": {}
  "/api/combat": {}
  "/api/cultivator": {}
  "/api/cultivator/migrate": {}
  "/api/cultivator/techniques": {}
  "/api/cultivator/use-item": {}
  "/api/dream": {}
  "/api/encounter": {}
  "/api/events": {}
  "/api/exchange": {}
  "/api/family": {}
  "/api/family-dialogue": {}
  "/api/heal": {}
  "/api/health": {}
  "/api/location-event": {}
  "/api/location-npc": {}
  "/api/narrative": {}
  "/api/narrative/retry": {}
  "/api/neighbors": {}
  "/api/npc-chat": {}
  "/api/properties": {}
  "/api/reading": {}
  "/api/reincarnation": {}
  "/api/reincarnation-altar": {}
  "/api/resolve-event": {}
  "/api/savings": {}
  "/api/secret-realm": {}
  "/api/settings": {}
  "/api/settings/list-models": {}
  "/api/shop": {}
  "/api/short-video": {}
  "/api/spirit-pet": {}
  "/api/streets": {}
  "/api/talent-slot": {}
  "/api/travel": {}
  "/api/use-item": {}
  "/api/warmup": {}
  "/api/weather": {}
  "/arcade": {}
  "/assets": {}
  "/card-preview": {}
  "/class-enroll": {}
  "/create": {}
  "/dashboard": {}
  "/dev": {}
  "/dreams": {}
  "/exchange": {}
  "/history": {}
  "/life": {}
  "/location-event": {}
  "/location-npcs": {}
  "/login": {}
  "/neighbors": {}
  "/personality": {}
  "/phone": {}
  "/reading": {}
  "/reincarnation": {}
  "/relationships": {}
  "/savings": {}
  "/secret-realm": {}
  "/shop": {}
  "/short-video": {}
  "/spirit-pet": {}
  "/streets": {}
  "/weather": {}
  "/world": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
