// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/arcade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arcade">> = Specific
  const handler = {} as typeof import("../../../src/app/arcade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/card-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/card-preview">> = Specific
  const handler = {} as typeof import("../../../src/app/card-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/class-enroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/class-enroll">> = Specific
  const handler = {} as typeof import("../../../src/app/class-enroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../../src/app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev">> = Specific
  const handler = {} as typeof import("../../../src/app/dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dreams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dreams">> = Specific
  const handler = {} as typeof import("../../../src/app/dreams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/exchange/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exchange">> = Specific
  const handler = {} as typeof import("../../../src/app/exchange/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/life/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/life">> = Specific
  const handler = {} as typeof import("../../../src/app/life/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/location-event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/location-event">> = Specific
  const handler = {} as typeof import("../../../src/app/location-event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/location-npcs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/location-npcs">> = Specific
  const handler = {} as typeof import("../../../src/app/location-npcs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/neighbors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/neighbors">> = Specific
  const handler = {} as typeof import("../../../src/app/neighbors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/personality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personality">> = Specific
  const handler = {} as typeof import("../../../src/app/personality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/phone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phone">> = Specific
  const handler = {} as typeof import("../../../src/app/phone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reading">> = Specific
  const handler = {} as typeof import("../../../src/app/reading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reincarnation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reincarnation">> = Specific
  const handler = {} as typeof import("../../../src/app/reincarnation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/relationships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/relationships">> = Specific
  const handler = {} as typeof import("../../../src/app/relationships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/savings">> = Specific
  const handler = {} as typeof import("../../../src/app/savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/secret-realm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/secret-realm">> = Specific
  const handler = {} as typeof import("../../../src/app/secret-realm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../../src/app/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/short-video/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/short-video">> = Specific
  const handler = {} as typeof import("../../../src/app/short-video/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/spirit-pet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/spirit-pet">> = Specific
  const handler = {} as typeof import("../../../src/app/spirit-pet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/streets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/streets">> = Specific
  const handler = {} as typeof import("../../../src/app/streets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/weather/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weather">> = Specific
  const handler = {} as typeof import("../../../src/app/weather/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/world/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/world">> = Specific
  const handler = {} as typeof import("../../../src/app/world/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/action/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/action">> = Specific
  const handler = {} as typeof import("../../../src/app/api/action/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/api/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/advance-quarter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/advance-quarter">> = Specific
  const handler = {} as typeof import("../../../src/app/api/advance-quarter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/advance-year/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/advance-year">> = Specific
  const handler = {} as typeof import("../../../src/app/api/advance-year/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/alchemy/formulas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alchemy/formulas">> = Specific
  const handler = {} as typeof import("../../../src/app/api/alchemy/formulas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/alchemy/refine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alchemy/refine">> = Specific
  const handler = {} as typeof import("../../../src/app/api/alchemy/refine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/arcade/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/arcade">> = Specific
  const handler = {} as typeof import("../../../src/app/api/arcade/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/auto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/auto">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/auto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/class-enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/class-enroll">> = Specific
  const handler = {} as typeof import("../../../src/app/api/class-enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/combat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/combat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cultivator/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cultivator/migrate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cultivator/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cultivator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cultivator">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cultivator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cultivator/techniques/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cultivator/techniques">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cultivator/techniques/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cultivator/use-item/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cultivator/use-item">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cultivator/use-item/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dream">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/encounter/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/encounter">> = Specific
  const handler = {} as typeof import("../../../src/app/api/encounter/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/exchange/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange">> = Specific
  const handler = {} as typeof import("../../../src/app/api/exchange/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/family-dialogue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family-dialogue">> = Specific
  const handler = {} as typeof import("../../../src/app/api/family-dialogue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/family/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/family">> = Specific
  const handler = {} as typeof import("../../../src/app/api/family/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/heal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/heal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/location-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/location-event">> = Specific
  const handler = {} as typeof import("../../../src/app/api/location-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/location-npc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/location-npc">> = Specific
  const handler = {} as typeof import("../../../src/app/api/location-npc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/narrative/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/narrative/retry">> = Specific
  const handler = {} as typeof import("../../../src/app/api/narrative/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/narrative/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/narrative">> = Specific
  const handler = {} as typeof import("../../../src/app/api/narrative/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/neighbors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/neighbors">> = Specific
  const handler = {} as typeof import("../../../src/app/api/neighbors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/npc-chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/npc-chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/npc-chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties">> = Specific
  const handler = {} as typeof import("../../../src/app/api/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reading">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reincarnation-altar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reincarnation-altar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reincarnation-altar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reincarnation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reincarnation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reincarnation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/resolve-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resolve-event">> = Specific
  const handler = {} as typeof import("../../../src/app/api/resolve-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/savings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/savings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/savings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/secret-realm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secret-realm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/secret-realm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/list-models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/list-models">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/list-models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shop">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/short-video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/short-video">> = Specific
  const handler = {} as typeof import("../../../src/app/api/short-video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/spirit-pet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/spirit-pet">> = Specific
  const handler = {} as typeof import("../../../src/app/api/spirit-pet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/streets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/streets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/streets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/talent-slot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/talent-slot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/talent-slot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/travel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/travel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/travel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/use-item/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/use-item">> = Specific
  const handler = {} as typeof import("../../../src/app/api/use-item/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/warmup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warmup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/warmup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../../src/app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
